import csv
 
with open('whales.csv', 'w') as csvfile:
    filewriter = csv.writer(csvfile, delimiter=',',
                            quotechar='|', quoting=csv.QUOTE_MINIMAL)
    filewriter.writerow(['fname', 'label'])
    filewriter.writerow(['neg_00.wav', 'Negative'])
    filewriter.writerow(['neg_01.wav', 'Negative'])
    filewriter.writerow(['neg_02.wav', 'Negative'])
    filewriter.writerow(['neg_03.wav', 'Negative'])
    filewriter.writerow(['neg_04.wav', 'Negative'])
    filewriter.writerow(['neg_05.wav', 'Negative'])
    filewriter.writerow(['neg_06.wav', 'Negative'])
    filewriter.writerow(['neg_07.wav', 'Negative'])
    filewriter.writerow(['neg_08.wav', 'Negative'])
    filewriter.writerow(['neg_09.wav', 'Negative'])
    filewriter.writerow(['neg_10.wav', 'Negative'])
    filewriter.writerow(['neg_11.wav', 'Negative'])
    filewriter.writerow(['neg_12.wav', 'Negative'])
    filewriter.writerow(['neg_13.wav', 'Negative'])
    filewriter.writerow(['neg_14.wav', 'Negative'])
    filewriter.writerow(['neg_15.wav', 'Negative'])
    filewriter.writerow(['neg_16.wav', 'Negative'])
    filewriter.writerow(['neg_17.wav', 'Negative'])
    filewriter.writerow(['neg_18.wav', 'Negative'])
    # filewriter.writerow(['neg_19.wav', 'Negative'])
    # filewriter.writerow(['neg_20.wav', 'Negative'])
    # filewriter.writerow(['neg_21.wav', 'Negative'])
    # filewriter.writerow(['neg_22.wav', 'Negative'])
    # filewriter.writerow(['neg_23.wav', 'Negative'])
    # filewriter.writerow(['neg_24.wav', 'Negative'])
    filewriter.writerow(['pos_00.wav', 'Positive'])
    filewriter.writerow(['pos_01.wav', 'Positive'])
    filewriter.writerow(['pos_02.wav', 'Positive'])
    filewriter.writerow(['pos_03.wav', 'Positive'])
    filewriter.writerow(['pos_04.wav', 'Positive'])
    filewriter.writerow(['pos_05.wav', 'Positive'])
    filewriter.writerow(['pos_06.wav', 'Positive'])
    filewriter.writerow(['pos_07.wav', 'Positive'])
    filewriter.writerow(['pos_08.wav', 'Positive'])
    filewriter.writerow(['pos_09.wav', 'Positive'])
    filewriter.writerow(['pos_10.wav', 'Positive'])
    filewriter.writerow(['pos_11.wav', 'Positive'])
    filewriter.writerow(['pos_12.wav', 'Positive'])
    filewriter.writerow(['pos_13.wav', 'Positive'])
    filewriter.writerow(['pos_14.wav', 'Positive'])
    filewriter.writerow(['pos_15.wav', 'Positive'])
    filewriter.writerow(['pos_16.wav', 'Positive'])
    filewriter.writerow(['pos_17.wav', 'Positive'])
    filewriter.writerow(['pos_18.wav', 'Positive'])